version: '3'

services: 

  deluge:
    build: 
      context: deluge
      dockerfile: Dockerfile
    volumes:
      - ./config:/root/.config/deluge
      - ./downloads:/root/Downloads
    ports: 
      - "8112:8112"
    network_mode: "host"
    restart: unless-stopped
    command:  ['-i', '0.0.0.0', '-p', '8112', '-L', 'INFO']
  
  samba:
    build: 
      context: samba
      dockerfile: Dockerfile
    ports: 
      - "139:139"
      - "445:445"
      - "137:137/udp"
      - "138:138/udp"      
    volumes:
      - ./downloads:/mount
    restart: unless-stopped      
    command: ["-s", "Deluge Downloads;/mount", "-p"]
