version: '3'

services: 

  deluge:
    image: kotaimen/deluge
    volumes:
      - ./config:/root/.config/deluge
      - /mnt/m2/downloads:/root/Downloads
    ports: 
      - "8112:8112"
    network_mode: "host"
    restart: unless-stopped
    command:  ['-i', '0.0.0.0', '-p', '8112', '-L', 'INFO']
