name: Build and Push

on:
  schedule:
    - cron: "0 6 * * 1" # At 06:00 on Monday.
  push:
    branches: [ master ]

jobs:

  bake:
    name: Deluge
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - 
        name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
      - 
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Build and push
        id: docker_build
        uses: docker/bake-action@v1.6.0
        with:
          push: true
