name: Build and Push

on:

  push:
    branches: [ master ]
  workflow_dispatch:
    inputs:

jobs:

  Release:
    name: Deluge
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v4
      - 
        name: Setup QEMU
        uses: docker/setup-qemu-action@v3
      - 
        name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
      - 
        name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/bake-action@v6
        with:
          push: true
