name: ci

on:
  push:
    branches: [ master ]

jobs:

  bake:
    name: Deluge
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v2    
      - 
        name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
      - 
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Build and push
        id: docker_build
        uses: docker/bake-action@v1.4.2
        with:
          push: true
